### ISSUE TITLE
Questions about global_depth and lwlr_depth

### ISSUE THREAD

**Issue by Vardure** [guangkaixu/BoostingDepth#1]
Dear authors,
     The input for linear regression for e.q.2 in the paper is predicted depth, however, I found that in your implementation, you first refine the predicted depth using global linear regression, then the result serves as locally linear regression's input. Could you please explain it more clearly?

**Comment by ChiyuanFeng** [comment]
According to the paper:"Therefore, we propose to conduct global recovery strategy to monocular depth first, and restrict the solution to be simple by adding an ℓ2 regularization on the shift"

**Comment by ChiyuanFeng** [comment]
> According to the paper:"Therefore, we propose to conduct global recovery strategy to monocular depth first, and restrict the solution to be simple by adding an ℓ2 regularization on the shift"

According to the paper:"Therefore, we propose to conduct global recovery strategy to monocular depth first, and restrict the solution to be simple by adding an ℓ2 regularization on the shift"

**Comment by ChiyuanFeng** [comment]
> 

According to the paper:"Therefore, we propose to conduct global recovery strategy to monocular depth first, and restrict the solution to be simple by adding an ℓ2 regularization on the shift"

**Comment by ChiyuanFeng** [comment]
> Dear authors, The input for linear regression for e.q.2 in the paper is predicted depth, however, I found that in your implementation, you first refine the predicted depth using global linear regression, then the result serves as locally linear regression's input. Could you please explain it more clearly?

According to the paper:"Therefore, we propose to conduct global recovery strategy to monocular depth first, and restrict the solution to be simple by adding an ℓ2 regularization on the shift"

**Comment by guangkaixu** [comment]
@ChiyuanFeng Thanks for your reading and replying!

@Vardure Hi, thanks for pointing out the writing mistakes in our paper. We have rewritten the formula and description in the latest version of our paper, which will release after submitted. As mention by @ChiyuanFeng, we perform the global recovery strategy to **recover global scale and shift first**, then conduct the local recovery strategy with shift regularization, which ensures the interpretability of the location-related scale map.

**Comment by ChiyuanFeng** [comment]
> @ChiyuanFeng Thanks for your reading and replying!
> 
> @Vardure Hi, thanks for pointing out the writing mistakes in our paper. We have rewritten the formula and description in the latest version of our paper, which will release after submitted. As mention by @ChiyuanFeng, we perform the global recovery strategy to **recover global scale and shift first**, then conduct the local recovery strategy with shift regularization, which ensures the interpretability of the location-related scale map.

You are welcome! And great job by the way, simple but efficient!
